dist: bionic
sudo: false
language: python
cache:
  pip: true
python:
- "2.7"
- "3.6"
- "3.7"
env: TOXENV=pep8, UPPER_CONSTRAINTS_FILE=https://raw.githubusercontent.com/sapcc/requirements/stable/train-m3/upper-constraints.txt
install: pip install tox-travis
script: tox
