#!/usr/bin/env bash

set -ex

export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y \
  python3-venv \
  build-essential python3-pip libpq-dev postgresql-client python3 python3-dev python3-distutils python3-psycopg2  git libpcre++-dev gettext libsqlite3-dev libsasl2-dev libldap2-dev libssl-dev libldap-common
python3 -m venv $HOME/.local/tools
source $HOME/.local/tools/bin/activate
pip install -U \
  pip \
  "tox<4" "six>=1.14.0" "crc<7.0.0"

export KEYSTONE_IDENTITY_BACKEND=ldap
export UPPER_CONSTRAINTS_FILE=https://raw.githubusercontent.com/sapcc/requirements/stable/2025.1-m3/upper-constraints.txt
cd source
tox -e py312
